globalThis.GRIDSHARD_CANON_MODULES = Object.freeze([
  {
    "id": "laser",
    "name_tr": "Lazer",
    "category": "saldırı",
    "rarity": "common",
    "unlock_arena": 1,
    "current_cost": 2,
    "max_hp": 100,
    "base_damage": 12,
    "unlock_trophies": 0
  },
  {
    "id": "shield",
    "name_tr": "Kalkan",
    "category": "savunma",
    "rarity": "common",
    "unlock_arena": 1,
    "current_cost": 3,
    "max_hp": 150,
    "base_damage": 0,
    "unlock_trophies": 0
  },
  {
    "id": "repair",
    "name_tr": "Onarım Modülü",
    "category": "destek",
    "rarity": "common",
    "unlock_arena": 1,
    "current_cost": 2,
    "max_hp": 100,
    "base_damage": 0,
    "unlock_trophies": 0
  },
  {
    "id": "cooler",
    "name_tr": "Soğutucu",
    "category": "destek",
    "rarity": "common",
    "unlock_arena": 1,
    "current_cost": 2,
    "max_hp": 100,
    "base_damage": 0,
    "unlock_trophies": 0
  },
  {
    "id": "battery",
    "name_tr": "Batarya",
    "category": "sistem",
    "rarity": "common",
    "unlock_arena": 1,
    "current_cost": 2,
    "max_hp": 120,
    "base_damage": 0,
    "unlock_trophies": 0
  },
  {
    "id": "amplifier",
    "name_tr": "Güçlendirici",
    "category": "destek",
    "rarity": "rare",
    "unlock_arena": 1,
    "current_cost": 3,
    "max_hp": 90,
    "base_damage": 0,
    "unlock_trophies": 0
  },
  {
    "id": "pulse_cannon",
    "name_tr": "Darbe Topu",
    "category": "saldırı",
    "rarity": "rare",
    "unlock_arena": 1,
    "current_cost": 3,
    "max_hp": 115,
    "base_damage": 32,
    "unlock_trophies": 50
  },
  {
    "id": "armor",
    "name_tr": "Zırh",
    "category": "savunma",
    "rarity": "common",
    "unlock_arena": 1,
    "current_cost": 2,
    "max_hp": 180,
    "base_damage": 0,
    "unlock_trophies": 150
  },
  {
    "id": "emp",
    "name_tr": "EMP",
    "category": "sabotaj",
    "rarity": "rare",
    "unlock_arena": 1,
    "current_cost": 3,
    "max_hp": 80,
    "base_damage": 0,
    "unlock_trophies": 250
  },
  {
    "id": "missile_launcher",
    "name_tr": "Füze Fırlatıcı",
    "category": "saldırı",
    "rarity": "rare",
    "unlock_arena": 2,
    "current_cost": 3,
    "max_hp": 105,
    "base_damage": 28,
    "unlock_trophies": 375
  },
  {
    "id": "targeting_computer",
    "name_tr": "Hedefleme Bilgisayarı",
    "category": "destek",
    "rarity": "rare",
    "unlock_arena": 2,
    "current_cost": 3,
    "max_hp": 85,
    "base_damage": 0,
    "unlock_trophies": 525
  },
  {
    "id": "arc_cannon",
    "name_tr": "Ark Topu",
    "category": "saldırı",
    "rarity": "rare",
    "unlock_arena": 3,
    "current_cost": 4,
    "max_hp": 100,
    "base_damage": 20,
    "unlock_trophies": 650
  },
  {
    "id": "barrier",
    "name_tr": "Bariyer",
    "category": "savunma",
    "rarity": "rare",
    "unlock_arena": 3,
    "current_cost": 3,
    "max_hp": 165,
    "base_damage": 0,
    "unlock_trophies": 750
  },
  {
    "id": "capacitor",
    "name_tr": "Kapasitör",
    "category": "sistem",
    "rarity": "rare",
    "unlock_arena": 3,
    "current_cost": 2,
    "max_hp": 90,
    "base_damage": 0,
    "unlock_trophies": 850
  },
  {
    "id": "drone_bay",
    "name_tr": "Dron Üssü",
    "category": "saldırı",
    "rarity": "rare",
    "unlock_arena": 4,
    "current_cost": 3,
    "max_hp": 110,
    "base_damage": 8,
    "unlock_trophies": 975
  },
  {
    "id": "jammer",
    "name_tr": "Sinyal Bozucu",
    "category": "sabotaj",
    "rarity": "rare",
    "unlock_arena": 4,
    "current_cost": 3,
    "max_hp": 85,
    "base_damage": 0,
    "unlock_trophies": 1125
  },
  {
    "id": "railgun",
    "name_tr": "Ray Topu",
    "category": "saldırı",
    "rarity": "epic",
    "unlock_arena": 5,
    "current_cost": 4,
    "max_hp": 95,
    "base_damage": 40,
    "unlock_trophies": 1250
  },
  {
    "id": "reflector",
    "name_tr": "Yansıtıcı",
    "category": "savunma",
    "rarity": "epic",
    "unlock_arena": 5,
    "current_cost": 4,
    "max_hp": 110,
    "base_damage": 0,
    "unlock_trophies": 1350
  },
  {
    "id": "current_balancer",
    "name_tr": "Akım Dengeleyici",
    "category": "sistem",
    "rarity": "rare",
    "unlock_arena": 5,
    "current_cost": 3,
    "max_hp": 100,
    "base_damage": 0,
    "unlock_trophies": 1450
  },
  {
    "id": "virus",
    "name_tr": "Virüs",
    "category": "sabotaj",
    "rarity": "epic",
    "unlock_arena": 6,
    "current_cost": 4,
    "max_hp": 70,
    "base_damage": 0,
    "unlock_trophies": 1575
  },
  {
    "id": "overclock_unit",
    "name_tr": "Aşırı Hızlandırıcı",
    "category": "destek",
    "rarity": "epic",
    "unlock_arena": 6,
    "current_cost": 4,
    "max_hp": 80,
    "base_damage": 0,
    "unlock_trophies": 1725
  },
  {
    "id": "plasma_mortar",
    "name_tr": "Plazma Havanı",
    "category": "saldırı",
    "rarity": "epic",
    "unlock_arena": 7,
    "current_cost": 4,
    "max_hp": 100,
    "base_damage": 30,
    "unlock_trophies": 1850
  },
  {
    "id": "guardian_dome",
    "name_tr": "Muhafız Kubbesi",
    "category": "savunma",
    "rarity": "epic",
    "unlock_arena": 7,
    "current_cost": 4,
    "max_hp": 155,
    "base_damage": 0,
    "unlock_trophies": 1950
  },
  {
    "id": "nano_medic",
    "name_tr": "Nano Sağlıkçı",
    "category": "destek",
    "rarity": "rare",
    "unlock_arena": 7,
    "current_cost": 3,
    "max_hp": 95,
    "base_damage": 0,
    "unlock_trophies": 2050
  },
  {
    "id": "quantum_repeater",
    "name_tr": "Kuantum Tekrarlayıcı",
    "category": "saldırı",
    "rarity": "epic",
    "unlock_arena": 8,
    "current_cost": 4,
    "max_hp": 92,
    "base_damage": 24,
    "unlock_trophies": 2175
  },
  {
    "id": "chrono_relay",
    "name_tr": "Krono Rölesi",
    "category": "destek",
    "rarity": "epic",
    "unlock_arena": 8,
    "current_cost": 4,
    "max_hp": 88,
    "base_damage": 0,
    "unlock_trophies": 2325
  },
  {
    "id": "ion_spear",
    "name_tr": "İyon Mızrağı",
    "category": "saldırı",
    "rarity": "legendary",
    "unlock_arena": 9,
    "current_cost": 5,
    "max_hp": 100,
    "base_damage": 48,
    "unlock_trophies": 2450
  },
  {
    "id": "phase_armor",
    "name_tr": "Faz Zırhı",
    "category": "savunma",
    "rarity": "epic",
    "unlock_arena": 9,
    "current_cost": 4,
    "max_hp": 150,
    "base_damage": 0,
    "unlock_trophies": 2550
  },
  {
    "id": "swarm_fabricator",
    "name_tr": "Sürü Fabrikatörü",
    "category": "saldırı",
    "rarity": "epic",
    "unlock_arena": 9,
    "current_cost": 4,
    "max_hp": 105,
    "base_damage": 6,
    "unlock_trophies": 2650
  },
  {
    "id": "disruptor",
    "name_tr": "Kesici",
    "category": "sabotaj",
    "rarity": "legendary",
    "unlock_arena": 10,
    "current_cost": 5,
    "max_hp": 80,
    "base_damage": 0,
    "unlock_trophies": 2775
  },
  {
    "id": "precision_matrix",
    "name_tr": "Hassasiyet Matrisi",
    "category": "destek",
    "rarity": "epic",
    "unlock_arena": 10,
    "current_cost": 4,
    "max_hp": 90,
    "base_damage": 0,
    "unlock_trophies": 2925
  },
  {
    "id": "quantum_cannon",
    "name_tr": "Kuantum Topu",
    "category": "saldırı",
    "rarity": "legendary",
    "unlock_arena": 11,
    "current_cost": 5,
    "max_hp": 105,
    "base_damage": 58,
    "unlock_trophies": 3050
  },
  {
    "id": "phoenix_repair",
    "name_tr": "Anka Onarım",
    "category": "destek",
    "rarity": "legendary",
    "unlock_arena": 11,
    "current_cost": 5,
    "max_hp": 100,
    "base_damage": 0,
    "unlock_trophies": 3150
  },
  {
    "id": "prism_shield",
    "name_tr": "Prizma Kalkanı",
    "category": "savunma",
    "rarity": "legendary",
    "unlock_arena": 11,
    "current_cost": 5,
    "max_hp": 165,
    "base_damage": 0,
    "unlock_trophies": 3250
  },
  {
    "id": "singularity_projector",
    "name_tr": "Tekillik Projektörü",
    "category": "sabotaj",
    "rarity": "legendary",
    "unlock_arena": 12,
    "current_cost": 5,
    "max_hp": 90,
    "base_damage": 25,
    "unlock_trophies": 3375
  },
  {
    "id": "omega_amplifier",
    "name_tr": "Omega Güçlendirici",
    "category": "destek",
    "rarity": "legendary",
    "unlock_arena": 12,
    "current_cost": 5,
    "max_hp": 95,
    "base_damage": 0,
    "unlock_trophies": 3525
  }
]);
