"use strict";

const assert = require("assert");
const fs = require("fs");

const html = fs.readFileSync("./index.html", "utf8");
const app = fs.readFileSync("./src/app.js", "utf8");
const relay = fs.readFileSync("./src/relay-client.js", "utf8");
const css = fs.readFileSync("./src/canon.css", "utf8");

assert.ok(html.includes('data-screen-panel="avatar"'));
assert.ok(html.includes('data-screen-panel="daily-rewards"'));
assert.ok(html.includes('data-screen-panel="rewards"'));
assert.ok(html.includes("40 KADEMELİ SEZON YOLUNU AÇ"));
assert.ok(html.includes("HER 10 KADEMEDE BÜYÜK ÖDÜL"));
assert.ok(html.includes('id="monthly-login-track"'));
assert.ok(html.includes("3–24 saatte yenilenir"));
assert.ok(html.includes('id="lobby-profile-avatar"'));
assert.ok(html.includes('id="post-match-experience-reward"'));
assert.ok(html.includes("TAKIM BİLGİSİ"));
assert.ok(html.includes("Takıma dahil değil"));
assert.ok(html.includes('data-open-screen="daily-rewards"><strong>Günlük Ödüller</strong>'));
assert.ok(html.includes('data-open-screen="rewards"><strong>Sezon Ödülleri</strong>'));
assert.ok(html.includes('id="profile-featured-core-level"'));
assert.ok(!html.includes('id="core-detail-role"'));
assert.ok(!html.includes("Bir çekirdek kartına dokun"));
assert.ok(!html.includes("Modül Değişimi</span>"));
assert.ok(!html.includes("Güçlendirici Kullanımı</span>"));
assert.ok(!html.includes("Özel Hücre</strong>"));
assert.ok(!html.includes("AÇILMA ZAMANI"));
assert.ok(app.includes("function renderAvatarCustomization"));
assert.ok(app.includes("function moduleShardSymbolMarkup"));
assert.ok(app.includes('applyAvatarVisual(document.getElementById("lobby-profile-avatar"), avatarId, frameId)'));
assert.ok(app.includes('claimEngagementReward("login"'));
assert.ok(app.includes("season_chest_receipt"));
assert.ok(app.includes("claim_cooldown_hours: 3"));
assert.ok(app.includes("claim_cooldown_hours: 8"));
assert.ok(app.includes("claim_cooldown_hours: 16"));
assert.ok(app.includes("claim_cooldown_hours: 24"));
assert.ok(app.includes("const preset = battlePoolPresets[index] || null"));
assert.ok(app.includes("function beginEmptyBattlePoolPreset"));
assert.ok(!app.includes("Ödül sunucuda doğrulanıyor"));
assert.ok(!app.includes("Ödüller hesabına işlendi"));
assert.ok(!app.includes("sandık yuvasına eklendi"));
assert.ok(!app.includes('"rotate_module"'));
assert.ok(app.includes('`\${activeTitle} · 🏆 \${view.rating}`'));
assert.ok(relay.includes('["matchmaking_request_timeout", "request_timeout"]'));
assert.ok(css.includes('.season-reward-card[data-major="true"]'));
assert.ok(css.includes("grid-template-columns:1fr !important"));
assert.ok(css.includes("/* September 2026 product pass: clean rewards, full core art and port-free battle. */"));
assert.ok(html.includes('class="arena-path-footer"'));
assert.ok(html.includes('id="arena-detail-close"'));
assert.ok(html.includes('id="arena-leaderboard-button"'));
assert.ok(css.includes(".arena-detail-dialog[open] > .arena-path-footer"));
assert.ok(css.includes("position:sticky !important"));

console.log("beta43.2 profile and season contract passed");
